package CarsData

class CarsDataProvider {
    companion object {
        val carsData = listOf<CarsData>(
            CarsData(
                "Ford",
                "+11",
                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Ford_logo.svg/1280px-Ford_logo.svg.png"
            ),
            CarsData(
                "Chevrolet",
                "+15",
                "https://i0.wp.com/lockhartautomotive.ca/wp-content/uploads/2019/01/chevrolet.png?fit=256%2C256&ssl=1"
            ),
            CarsData(
                "Toyota",
                "+10",
                "https://i.pinimg.com/originals/53/85/9b/53859b2ba85979cd4bb753f2a5a346fe.png"
            ),
            CarsData(
                "Honda",
                "+9",
                "https://www.pngmart.com/files/1/Honda-Logo-PNG.png"
            ),
            CarsData(
                "Volkswagen",
                "+19",
                "https://cdn.iconscout.com/icon/free/png-256/free-volkswagen-3441311-2874760.png"
            ),
            CarsData(
                "BMW",
                "+14",
                "https://www.pngplay.com/wp-content/uploads/13/BMW-Logo-PNG-Photo-Image.png"
            ),
            CarsData(
                "Mercedes-Benz",
                "+11",
                "https://companiesmarketcap.com/img/company-logos/256/MBG.DE.png"
            ),
            CarsData(
                "Audi",
                "+9",
                "https://cdn.iconscout.com/icon/free/png-256/free-audi-5-282206.png?f=webp&w=256"
            ),
            CarsData(
                "Lexus",
                "+10",
                "https://cdn.iconscout.com/icon/free/png-256/free-lexus-7-827477.png"
            ),
            CarsData(
                "Nissan",
                "+11",
                "https://cdn.iconscout.com/icon/free/png-256/free-nissan-2227466-1853260.png"
            ),
            CarsData(
                "Hyundai",
                "+13",
                "https://cdn.iconscout.com/icon/free/png-256/free-hyundai-3441263-2874712.png"
            ),
            CarsData(
                "Kia",
                "+17",
                "https://upload.wikimedia.org/wikipedia/commons/1/13/Kia-logo.png"
            ),
            CarsData(
                "Mazda",
                "+16",
                "https://cdn.iconscout.com/icon/free/png-256/free-mazda-3-827488.png"
            ),
            CarsData(
                "GMC",
                "+13",
                "https://1000marcas.net/wp-content/uploads/2021/02/GMC-Logo.png"
            ),
            CarsData(
                "Alfa Romeo",
                "+22",
                "https://assets.stickpng.com/images/580b585b2edbce24c47b2c06.png"
            ),
            CarsData(
                "Subaru",
                "+10",
                "https://assets.stickpng.com/images/580b585b2edbce24c47b2cbf.png"
            ),
            CarsData(
                "Ferrari",
                "+7",
                "https://assets.stickpng.com/images/580b585b2edbce24c47b2c52.png"
            ),
            CarsData(
                "Volvo",
                "+12",
                "https://cdn.iconscout.com/icon/free/png-256/free-volvo-3441312-2874761.png"
            ),
            CarsData(
                "Dodge",
                "+12",
                "https://www.pngmart.com/files/22/Dodge-Logo-PNG-File.png"
            ),
            CarsData(
                "Tesla",
                "+10",
                "https://cdn.iconscout.com/icon/free/png-256/free-tesla-14-892143.png"
            ),
            CarsData(
                "Mitsubishi",
                "+28",
                "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Mitsubishi_logo.svg/2381px-Mitsubishi_logo.svg.png"
            ),
            CarsData(
                "Acura",
                "+15",
                "https://www.pngmart.com/files/10/Acura-Logo-PNG-File.png"
            ),
        )
    }
}