package CarsData

class CarsDataProvider {
    companion object {
        val carsData = listOf<CarsData>(
            CarsData(
                "Ford",
                "+11",
                "https://mediaclick.es/wp-content/uploads/2013/10/Ford1.jpg"
            ),
            CarsData(
                "Chevrolet",
                "+15",
                "https://i0.wp.com/lockhartautomotive.ca/wp-content/uploads/2019/01/chevrolet.png?fit=256%2C256&ssl=1"
            ),
            CarsData(
                "Toyota",
                "+10",
                "https://www.codinter.com/es/wp-content/uploads/sites/3/2018/01/logo-toyota-256x256.png"
            ),
            CarsData(
                "Honda",
                "+9",
                "https://cdn.iconscout.com/icon/free/png-256/free-honda-38-827481.png"
            ),
            CarsData(
                "Volkswagen",
                "+19",
                "https://cdn.iconscout.com/icon/free/png-256/free-volkswagen-3441311-2874760.png"
            ),
            CarsData(
                "BMW",
                "+14",
                "https://www.spainmotorent.es/wp-content/uploads/2018/07/bmw-logo.png"
            ),
            CarsData(
                "Mercedes-Benz",
                "+11",
                "https://companiesmarketcap.com/img/company-logos/256/MBG.DE.png"
            ),
            CarsData(
                "Audi",
                "+9",
                "https://cdn.iconscout.com/icon/free/png-256/free-audi-5-282206.png?f=webp&w=256"
            ),
            CarsData(
                "Lexus",
                "+10",
                "https://cdn.iconscout.com/icon/free/png-256/free-lexus-7-827477.png"
            ),
            CarsData(
                "Nissan",
                "+11",
                "https://cdn.iconscout.com/icon/free/png-256/free-nissan-2227466-1853260.png"
            ),
            CarsData(
                "Hyundai",
                "+13",
                "https://cdn.iconscout.com/icon/free/png-256/free-hyundai-3441263-2874712.png"
            ),
            CarsData(
                "Kia",
                "+17",
                "https://cdn.iconscout.com/icon/free/png-256/free-kia-202823.png"
            ),
            CarsData(
                "Mazda",
                "+16",
                "https://cdn.iconscout.com/icon/free/png-256/free-mazda-3-827488.png"
            ),
            CarsData(
                "Subaru",
                "+10",
                "https://logospng.org/download/subaru/subaru-256.png"
            ),
            CarsData(
                "Volvo",
                "+12",
                "https://cdn.iconscout.com/icon/free/png-256/free-volvo-3441312-2874761.png"
            ),
            CarsData(
                "Tesla",
                "+10",
                "https://cdn.iconscout.com/icon/free/png-256/free-tesla-14-892143.png"
            )
        )
    }
}